### ISSUE TITLE
Breakpoints groups and multipliers not supported. 

### ISSUE THREAD

**Issue by iberdinsky-skilld** [jenslind/drupal-breakpoints-scss#5]
According to: https://www.drupal.org/docs/8/theming-drupal-8/working-with-breakpoints-in-drupal-8 it is possible to join queries in groups. And use multipliers. Currently if use example from 
http://cgit.drupalcode.org/drupal/tree/core/modules/breakpoint/tests/themes/breakpoint_theme_test/breakpoint_theme_test.breakpoints.yml 
breakpoint file:

```
breakpoint_theme_test.mobile:
  label: mobile
  mediaQuery: '(min-width: 0px)'
  weight: 0
  multipliers:
    - 1x
breakpoint_theme_test.narrow:
  label: narrow
  mediaQuery: '(min-width: 560px)'
  weight: 1
  multipliers:
    - 1x
# Out of order breakpoint to test sorting.
breakpoint_theme_test.tv:
  label: tv
  mediaQuery: 'only screen and (min-width: 1220px)'
  weight: 3
  multipliers:
    - 1x
breakpoint_theme_test.wide:
  label: wide
  mediaQuery: '(min-width: 851px)'
  weight: 2
  multipliers:
    - 1x
breakpoint_theme_test.group2.narrow:
  label: narrow
  mediaQuery: '(min-width: 560px)'
  weight: 0
  multipliers:
    - 1x
    - 2x
  group: breakpoint_theme_test.group2
breakpoint_theme_test.group2.wide:
  label: wide
  mediaQuery: '(min-width: 851px)'
  weight: 1
  multipliers:
    - 1x
    - 2x
  group: breakpoint_theme_test.group2
```

Result will be:

```
$mobile: '(min-width: 0px)';
$narrow: '(min-width: 560px)';
$tv: 'only screen and (min-width: 1220px)';
$wide: '(min-width: 851px)';
$narrow: '(min-width: 560px)';
$wide: '(min-width: 851px)';

$drupal-breakpoints: (
  mobile: '(min-width: 0px)',
  narrow: '(min-width: 560px)',
  tv: 'only screen and (min-width: 1220px)',
  wide: '(min-width: 851px)',
  narrow: '(min-width: 560px)',
  wide: '(min-width: 851px)',
);

```
No multipliers and no groups.
